WIDTH = int (26 * 42)
HEIGHT = int (26 * 26)
SCALE_FACTOR = 3
TILE_SIZE = 26 * SCALE_FACTOR
HALF_W = 12 * SCALE_FACTOR
HALF_H = 6 * SCALE_FACTOR
ORIGIN_X = (WIDTH // 2) - (TILE_SIZE // 2)
ORIGIN_Y = HEIGHT // 4 - 100

INVENTORY_WIDTH = 128 * SCALE_FACTOR
INVENTORY_HEIGHT = 64 * SCALE_FACTOR

PADDING = SCALE_FACTOR * 3

ITEM_WIDTH = 16 * SCALE_FACTOR
ITEM_HEIGHT = 16 * SCALE_FACTOR